-- MySQL Script generated by MySQL Workbench
-- Tue Jul 13 14:11:19 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `project` DEFAULT CHARACTER SET utf8 ;
USE `project` ;

-- -----------------------------------------------------
-- Table `project`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`Users` (
  `idUsers` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `role` VARCHAR(45) NOT NULL DEFAULT 'USER',
  PRIMARY KEY (`idUsers`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`tasks` (
  `id_t` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `content` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_t`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`result`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`result` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Users_idUsers` INT NOT NULL,
  `tasks_id_t` INT NOT NULL,
  `result` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_group1_Users_idx` (`Users_idUsers` ASC) VISIBLE,
  INDEX `fk_group1_tasks1_idx` (`tasks_id_t` ASC) VISIBLE,
  CONSTRAINT `fk_group1_Users`
    FOREIGN KEY (`Users_idUsers`)
    REFERENCES `project`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_group1_tasks1`
    FOREIGN KEY (`tasks_id_t`)
    REFERENCES `project`.`tasks` (`id_t`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
